# Generated by Django 5.2.7 on 2025-11-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='family_id',
            new_name='familyId',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='user_id',
            new_name='userId',
        ),
    ]
