# Generated by Django 5.2.7 on 2025-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_rename_family_id_family_familyid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='id',
        ),
        migrations.AlterField(
            model_name='family',
            name='familyId',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
