# Generated by Django 5.2.7 on 2025-11-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_remove_family_id_alter_family_familyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='familyId',
            new_name='id',
        ),
    ]
