# Generated by Django 5.2.7 on 2025-11-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_rename_familyid_family_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='id',
            new_name='familyId',
        ),
    ]
